### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by rocketprogrammer** [WorldOfCarsRE/game-server#1]
- [x] Implement proper UberDOG server (Not really needed for test server)
- [x] Make ShardManager a proper UberDOG object, and not on the AI server for multiple district support (Not really needed for test server)
- [x] Implement player friends functionality (PlayerFriendsManager)
- [x] Implement all minigames (Having issues with the remaining unimplemented minigames, will figure this out after launch.)
- [x] Implement spawn points for each zone
- [x] Finish AI server functionality for multiplayer & singleplayer races (Multiplayer races will come after launch, singleplayer races are good to go.)
- [x] Filter whispers on the OTP server (setTalkWhisper)
